local function create_named_buf(name)
	local buf = vim.api.nvim_create_buf(true, false)
	vim.api.nvim_buf_set_name(buf, name)
	return buf
end

describe("GetUniqueDirPart", function()
	after_each(function()
		local bufs = vim.api.nvim_list_bufs()
		for _, i in pairs(bufs) do
			vim.api.nvim_buf_delete(i, {force = true})
		end
	end)
	it("does nothing when there are no conflicting names", function()
		create_named_buf("foo.txt")
		assert.same("", vim.fn.GetUniqueDirPart("foo.txt", "foo.txt"))
	end)
	it("returns unique part", function()
		create_named_buf("blah/foo.txt")
		create_named_buf("whee/foo.txt")
		assert.same("blah", vim.fn.GetUniqueDirPart("blah/foo.txt", "foo.txt"))
		assert.same("whee", vim.fn.GetUniqueDirPart("whee/foo.txt", "foo.txt"))
	end)
	it("returns unique part when there are parts in front of path that are different", function()
		create_named_buf("a/blah/foo.txt")
		create_named_buf("b/whee/foo.txt")
		assert.same("blah", vim.fn.GetUniqueDirPart("a/blah/foo.txt", "foo.txt"))
		assert.same("whee", vim.fn.GetUniqueDirPart("b/whee/foo.txt", "foo.txt"))
	end)
	it("returns only the unique part in the front of the file when there are 2 files with same dir length", function()
		create_named_buf("foo/bar/baz.txt")
		create_named_buf("one/bar/baz.txt")
		assert.same("foo", vim.fn.GetUniqueDirPart("foo/bar/baz.txt", "baz.txt"))
		assert.same("one", vim.fn.GetUniqueDirPart("one/bar/baz.txt", "baz.txt"))
	end)
	it("returns only the unique part in the front of the file for 3 files", function()
		create_named_buf("foo/bar/baz.txt")
		create_named_buf("one/bar/baz.txt")
		create_named_buf("whee/baz.txt")
		assert.same("foo/bar", vim.fn.GetUniqueDirPart("foo/bar/baz.txt", "baz.txt"))
		assert.same("one/bar", vim.fn.GetUniqueDirPart("one/bar/baz.txt", "baz.txt"))
		assert.same("whee", vim.fn.GetUniqueDirPart("whee/baz.txt", "baz.txt"))
	end)
	it("returns only the necessary unique part at the end of the file", function()
		create_named_buf("foo/bar/a/b/baz.txt")
		create_named_buf("hello/world/baz.txt")
		create_named_buf("goodbye/world/baz.txt")
		assert.same("b", vim.fn.GetUniqueDirPart("foo/bar/a/b/baz.txt", "baz.txt"))
		assert.same("hello/world", vim.fn.GetUniqueDirPart("hello/world/baz.txt", "baz.txt"))
		assert.same("goodbye/world", vim.fn.GetUniqueDirPart("goodbye/world/baz.txt", "baz.txt"))
	end)
end)

