#!/usr/bin/env bash

FILE="${1}"
REGEX='^(revert: )?(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .{1,50}'
MSG='Please adhere to the conventional commits guidelines\nCommit must start with (feat|fix|docs|style|refactor|perf|test|chore)'

if ! grep -iqE "${REGEX}" <(head -n 1 "${FILE}"); then
    echo -e "${MSG}" >&2
    exit 1
fi
